### ISSUE TITLE
incorrect frontier name

### ISSUE THREAD

**Issue by bruhwiler** [gordonwatts/snowmass-loi-words#34]
On your word cloud page, https://gordonwatts.github.io/snowmass-loi-words/wordcloud

"Communications" Frontier should be changed to "Community Engagement" Frontier

**Comment by gordonwatts** [comment]
Argh. Yes, that is an easy change! M bad!

**Comment by gordonwatts** [comment]
Ah - I had already fixed that. Excellent. Sorry I didn't close this earlier. If you see it in another place, feel free to re-open and let me know where it is. @bruhwiler ! Thanks for taking a look!
