### ISSUE TITLE
plot labels are too small

### ISSUE THREAD

**Issue by bruhwiler** [gordonwatts/snowmass-loi-words#35]
On your LOI page, https://gordonwatts.github.io/snowmass-loi-words/

It's not possible to read the plot labels, which significantly diminishes the value of the plot.

**Comment by gordonwatts** [comment]
I'll fix that. You'll have an easier time reading it when you actually have it full size: https://gordonwatts.github.io/snowmass-loi-words/assets/images/lois-by-frontier.png

**Comment by gordonwatts** [comment]
@bruhwiler -  I've increased the size of the labels. I've also made it so you can click-through to a vector-graphic representation of the plot so that it will scale without artifacts. Please, if you think there is more to do with the font sizes, feel free to re-open!
